#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Tool
#
VERSION = 0.1
PACKAGE_NAME = DataBasinTool
TOOL_NAME = DataBasinTool
DataBasinTool_TOOL_ICON = 


#
# Libraries
#
DataBasinTool_LIBRARIES_DEPEND_UPON += -lDataBasinKit 

#
# Resource files
#
DataBasinTool_RESOURCE_FILES = \
Resources/Version \


#
# Header files
#
DataBasinTool_HEADER_FILES = \
DBTLogger.h \
ToolController.h

#
# Objective-C Class files
#
DataBasinTool_OBJC_FILES = \
DBTLogger.m \
ToolController.m

#
# Other sources
#
DataBasinTool_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
